import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@/app/globals.css"
import { cn } from "@/lib/utils"
require("@/lib/database");
import { ThemeProvider } from "@/components/FeaturePanel/theme-provider";
import SidebarStateProvider from '@/components/FeaturePanel/sidebarState';

const inter = Inter({ subsets: ['latin'] })




export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={cn(
                "min-h-screen bg-background font-sans antialiased",
                "text-text",
            )}>
                <SidebarStateProvider>
                    <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
                        {children}
                    </ThemeProvider>
                </SidebarStateProvider>
            </body>
        </html>
    )
}

